name: Release JSReport Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
  workflow_dispatch:

env:
  HELM_REPO_URL: https://ankosoftware.github.io/jsreport-helm
  CHART_PATH: .

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Lint Helm Chart
        run: |
          helm lint charts/jsreport

      - name: Package Helm Chart
        run: |
          helm package charts/jsreport

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
